spring:
  datasource:
    url: jdbc:mariadb://foreverpet-mariadb.cerwgfjzzflp.ap-northeast-2.rds.amazonaws.com:3306/foreverpet
    username: admin
    password: foreverpet
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K
oauth:
  kakao:
    client-id: ef70ead256236ff245dd289a71f416f3
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com