spring:
  datasource:
    url: jdbc:mariadb://foreverpet-mariadb.cerwgfjzzflp.ap-northeast-2.rds.amazonaws.com:3306/foreverpet
    username: admin
    password: foreverpet
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  profiles:
    active: local